FROM ubuntu:latest
LABEL "Auther"="Sasi"
LABEL "Project"="html_template"
RUN apt update && apt install apache2 -y
CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
EXPOSE 80
WORKDIR /var/www/html
VOLUME /var/log/apache2
ADD html_template.tar.gz /var/www/html
~
