version: "1.0"
services:
  vproapp:
    build: 
      context: ./Docker-files/app
    image: sasidharsaz/vproapp
    container_name: vproapp
    ports:
    - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps
    depends_on:
    - vprodb


  vprodb:
    build: 
      context: ./Docker-files/db
    image: sasidharsaz/vprofiledb
    container_name: vprodb
    ports:
      - "3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=vprodbpass
    volumes:
      - vprodbdata:/var/lib/mysql
    depends_on:
    - vprocache01  

  vprocache01:
    build: memcached
    container_name: vprocache01
    ports:
      - "11211:11211"
    depends_on:
    - vpromq01

  vpromq01:
    image: rabbitmq
    container_name: vpromq01
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  vproweb:
    build: 
      context: ./Docker-files/web
    image: sasidharsaz/vprofileweb
    container_name: vproweb
    ports:
      - "80:80"    


volumes:
  vprodbdata: {}
  vproappdata: {}