version: '3.8'
services:
  vprodb:
    build:
     context: ./Docker-files/db  # <-- build from Dockerfile in ./Docker-files/db
    image: sasidharsaz/vprofiledb
    container_name: vprodb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass
      - MYSQL_DATABASE=accounts

  vprocache01:
    image: memcached
    container_name: vprocache01
    ports:
      - "11211:11211"

  vpromq01:
    image: rabbitmq
    container_name: vpromq01
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  vproapp:
    build:
      context: ./Docker-files/app
    image: sasidharsaz/vprofileapp
    container_name: vproapp
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps
    depends_on:
      - vprodb
      - vprocache01
      - vpromq01

  vproweb:
    build:
      context: ./Docker-files/web
    image: sasidharsaz/vprofileweb
    container_name: vproweb
    ports:
      - "80:80"
    depends_on:
      - vproapp

volumes:
   vprodbdata: {}
   vproappdata: {}
